NES-2140: add command to list and install plugin to resource
TinxHQ/nestbox-confd-client pull request #29
Opened 2024-07-16 12:17 UTC by ja0x

2024-07-16 13:22 UTC, sduthil requested changes

2024-07-16 13:22 UTC, sduthil commented on nestbox_confd_client/commands/plugins.py
> +    def list_customer_installs(self, plugin_uuid, tenant_uuid=None, **kwargs):
Documentation is missing in the README

2024-07-16 13:22 UTC, sduthil commented on nestbox_confd_client/commands/plugins.py
> +        for key, value in kwargs.items():
Do we really need the loop? E.g.
```
params = dict(kwargs)
if uuids := params.get('uuids'):
    params['uuids'] = ','.join(uuids)
```

2024-07-16 14:32 UTC, ja0x commented on nestbox_confd_client/commands/plugins.py
> +        for key, value in kwargs.items():
+1

2024-07-16 14:32 UTC, ja0x commented on nestbox_confd_client/commands/plugins.py
> +    def list_customer_installs(self, plugin_uuid, tenant_uuid=None, **kwargs):
Oops, will add

2024-07-16 14:50 UTC, ja0x commented
Unsure about the wording of `install_for_{customer|reseller|location}`.  Should it be `install_to_{customer|reseller|location}` to make it clearer?

2024-07-17 16:12 UTC, sduthil approved these changes

2024-07-17 16:16 UTC, merged